### ISSUE TITLE
[Bug] Today's data not available on workout sensor

### ISSUE THREAD

**Issue by akeslo** [nitobuendia/oura-custom-component#29]
Hey @nitobuendia - working my way down the list backporting what I use to this component. Looks like I'm hitting a similar issue with the workout sensor that could benefit from the code update here:  https://github.com/nitobuendia/oura-custom-component/issues/26

![image](https://user-images.githubusercontent.com/3003773/213885776-f1d84cde-b40a-4f02-b8a1-73d3bf86e2bf.png)

Config
```
     workouts:
       name: oura_workouts
       max_backfill: 0
       monitored_dates:
        - 0d_ago
        - 1d_ago
        - 7d_ago
  ```

![image](https://user-images.githubusercontent.com/3003773/213885832-b6377702-54ee-4827-b339-b2f77e4317d3.png)

**Comment by nitobuendia** [comment]
Both sensors will use the same base sensor and should receive the update. In other words, this should be solved with the same fix as #26.

**Comment by akeslo** [comment]
@nitobuendia didn't seem to fix it for me on my end.  Same config as above, the sensor returns "Unknown". 

![image](https://user-images.githubusercontent.com/3003773/214207745-ee4885f2-a119-4533-9116-8f7ff6c534e8.png)

**Comment by nitobuendia** [comment]
What do you see on attributes when the state is unknown?

**Comment by akeslo** [comment]
> What do you see on attributes when the state is unknown?

There are zero attributes

**Comment by nitobuendia** [comment]
That's not expected. Are you sure that's not an old sensor? Can you see if you can remove it or if there's an oura_workouts_2. Is your config the same shared before?

**Comment by akeslo** [comment]
Very odd, it doesn't appear to be an old sensor.  I even tried swapping the name. Not sure what it could be.  I don't see anything useful in the logs.  

![image](https://user-images.githubusercontent.com/3003773/215009480-0972fc07-732f-436b-be40-4612524d9059.png)



Config is now

```
  - platform: oura
    access_token: <token>
    scan_interval: 600
    sensors:
     sleep:
       name: oura_sleep_metrics
       max_backfill: 0
       monitored_dates:
        - 0d_ago
        - 1d_ago
        - 2d_ago
        - 3d_ago
        - 4d_ago
        - 5d_ago
        - 6d_ago
        - 7d_ago
        - 8d_ago
     sleep_periods:
       name: oura_sleep_periods
       max_backfill: 0
       monitored_dates:
        - 0d_ago
        - 1d_ago
        - 7d_ago       
     sleep_score:
       name: oura_sleep_score
       max_backfill: 0 
       monitored_dates:
        - 0d_ago
        - 1d_ago
        - 2d_ago
        - 3d_ago
        - 4d_ago
        - 5d_ago
        - 6d_ago
        - 7d_ago
        - 8d_ago
     workouts:
        name: oura_workouts
        max_backfill: 0
        monitored_dates:
        - yesterday
        - 0d_ago
        - 1d_ago
        - 2d_ago
        - 3d_ago
        - 4d_ago
        - 5d_ago
        - 6d_ago
        - 7d_ago
        - 8d_ago
     activity:
       name: oura_activity
       max_backfill: 0
       monitored_dates:
        - 0d_ago
        - 1d_ago
        - 2d_ago
        - 3d_ago
        - 4d_ago
        - 5d_ago
        - 6d_ago
        - 7d_ago
        - 8d_ago
       monitored_variables:
        - day
        - active_calories
        - high_activity_time
        - low_activity_time
        - medium_activity_time
        - non_wear_time
        - resting_time
        - sedentary_time
        - score
        - target_calories
        - total_calories
        - steps
     heart_rate:
       name: oura_heartrate
       max_backfill: 0
       monitored_dates:
        - 0d_ago
     readiness:
       name: oura_readiness
       max_backfill: 0
       monitored_dates:
        - 0d_ago
        - 1d_ago
        - 2d_ago
        - 3d_ago
        - 4d_ago
        - 5d_ago
        - 6d_ago
        - 7d_ago
        - 8d_ago
```

**Comment by nitobuendia** [comment]
Your screenshot shows a sensor called `oura_recoredworkouts` which (has a typo) and doesn't appear on your config.

**Comment by akeslo** [comment]
> 

I temporarily changed it to that name to prove it wasn't a ghost entity or old entity, sorry if that wasn't clear.  typo is irrelevant, no matter what name I use I get unknown and no attributes.  Is there any logging I can enable with this integration? I have all logs set to info and I'm not seeing much.

Thanks.

![image](https://user-images.githubusercontent.com/3003773/215110169-22b14434-e909-4ea4-9c5e-4cd0b26f1bf2.png)

**Comment by akeslo** [comment]
I just temporarily renamed the sensor to oura_workouts2, same thing....

```
     workouts:
        name: oura_workouts2
        max_backfill: 0
        monitored_dates:
        - yesterday
        - 0d_ago
        - 1d_ago
        - 2d_ago
        - 3d_ago
        - 4d_ago
        - 5d_ago
        - 6d_ago
        - 7d_ago
        - 8d_ago
```


![image](https://user-images.githubusercontent.com/3003773/215111184-17c4e1b7-1586-4729-bcbb-17ee803a4622.png)

**Comment by nitobuendia** [comment]
Thanks for posting with matching config and screenshot.

I can reproduce the issue too with the same configuration.

You can enable logs with the [logger component](https://www.home-assistant.io/integrations/logger/), but I do not expect this to return a lot more of what you may be getting already.

A sample config:

```yaml
default: info
logs:
  homeassistant.custom_components.oura: debug
  custom_components.oura: debug
```

**Comment by nitobuendia** [comment]
This looks different than the original issue, so I've opened #31 to track it.
